// Unified tools configuration for 3D Playground
// Using devicon slugs for maximum compatibility

export const ALL_TOOLS = [
  // ═══ DATA ═══
  {
    id: 'python',
    name: 'Python',
    slug: 'python',
    category: 'Data',
    desc: 'Versatile programming language for data science, automation, and web development.',
    color: '#3776AB',
    emoji: '🐍',
  },
  {
    id: 'sql',
    name: 'SQL',
    slug: 'mysql',
    category: 'Data',
    desc: 'Structured Query Language for managing and analyzing relational databases.',
    color: '#4479A1',
    emoji: '🗄️',
  },
  {
    id: 'pandas',
    name: 'Pandas',
    slug: 'pandas',
    category: 'Data',
    desc: 'Powerful Python library for data manipulation and analysis with DataFrames.',
    color: '#150458',
    emoji: '🐼',
  },
  {
    id: 'scikit',
    name: 'Scikit-learn',
    slug: 'scikitlearn',
    category: 'Data',
    desc: 'Machine learning library for Python. Classification, regression, clustering.',
    color: '#F7931E',
    emoji: '🧠',
  },
  {
    id: 'powerbi',
    name: 'Power BI',
    slug: 'powerbi',
    category: 'Data',
    desc: 'Business intelligence tool for interactive data visualization and dashboards.',
    color: '#F2C811',
    emoji: '📊',
  },
  {
    id: 'looker',
    name: 'Looker Studio',
    slug: 'googlecloud',
    category: 'Data',
    desc: 'Cloud-based business intelligence and analytics platform.',
    color: '#4285F4',
    emoji: '🔍',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    slug: 'mysql',
    category: 'Data',
    desc: 'Popular open-source relational database management system.',
    color: '#4479A1',
    emoji: '🐬',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'Data',
    desc: 'Advanced open-source object-relational database.',
    color: '#336791',
    emoji: '🐘',
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    slug: 'fastapi',
    category: 'Data',
    desc: 'Modern Python web framework for building APIs with auto validation.',
    color: '#009688',
    emoji: '⚡',
  },

  // ═══ DEV ═══
  {
    id: 'javascript',
    name: 'JavaScript',
    slug: 'javascript',
    category: 'Dev',
    desc: 'The language of the web. Essential for frontend and backend development.',
    color: '#F7DF1E',
    emoji: '💛',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    slug: 'typescript',
    category: 'Dev',
    desc: 'JavaScript with syntax for types. Better tooling and fewer bugs.',
    color: '#3178C6',
    emoji: '🔷',
  },
  {
    id: 'react',
    name: 'React',
    slug: 'react',
    category: 'Dev',
    desc: 'Popular JavaScript library for building user interfaces.',
    color: '#61DAFB',
    emoji: '⚛️',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    slug: 'nextjs',
    category: 'Dev',
    desc: 'React framework with SSR and static site generation.',
    color: '#000000',
    emoji: '▲',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    slug: 'nodejs',
    category: 'Dev',
    desc: 'JavaScript runtime built on Chrome\'s V8 engine.',
    color: '#339933',
    emoji: '🟢',
  },
  {
    id: 'php',
    name: 'PHP',
    slug: 'php',
    category: 'Dev',
    desc: 'Server-side scripting language for web development.',
    color: '#777BB4',
    emoji: '🐘',
  },
  {
    id: 'laravel',
    name: 'Laravel',
    slug: 'laravel',
    category: 'Dev',
    desc: 'PHP framework for web artisans with elegant syntax.',
    color: '#FF2D20',
    emoji: '🎼',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    slug: 'tailwindcss',
    category: 'Dev',
    desc: 'Utility-first CSS framework for rapid UI development.',
    color: '#06B6D4',
    emoji: '💨',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    slug: 'prisma',
    category: 'Dev',
    desc: 'Next-generation ORM for Node.js and TypeScript.',
    color: '#5A67D8',
    emoji: '🔺',
  },
  {
    id: 'vscode',
    name: 'VS Code',
    slug: 'visualstudiocode',
    category: 'Dev',
    desc: 'Powerful code editor with rich extension ecosystem.',
    color: '#007ACC',
    emoji: '💻',
  },
  {
    id: 'git',
    name: 'Git',
    slug: 'git',
    category: 'Dev',
    desc: 'Distributed version control system for tracking changes.',
    color: '#F05032',
    emoji: '📦',
  },

  // ═══ DESIGN ═══
  {
    id: 'figma',
    name: 'Figma',
    slug: 'figma',
    category: 'Design',
    desc: 'Collaborative interface design tool in the browser.',
    color: '#F24E1E',
    emoji: '🎨',
  },
  {
    id: 'canva',
    name: 'Canva',
    slug: 'canva',
    category: 'Design',
    desc: 'Online design platform for social media graphics and more.',
    color: '#00C4CC',
    emoji: '🖼️',
  },

  // ═══ VIDEO ═══
  {
    id: 'davinci',
    name: 'DaVinci Resolve',
    slug: 'davinciresolve',
    category: 'Video',
    desc: 'Professional video editing and color grading software.',
    color: '#6EBP49',
    emoji: '🎬',
  },
  {
    id: 'premiere',
    name: 'Premiere Pro',
    slug: 'adobe',
    category: 'Video',
    desc: 'Industry-leading video editing software.',
    color: '#9999FF',
    emoji: '🎥',
  },
  {
    id: 'capcut',
    name: 'CapCut',
    slug: 'capcut',
    category: 'Video',
    desc: 'User-friendly video editor for social media content.',
    color: '#000000',
    emoji: '✂️',
  },
];

export const TOOL_CATEGORIES = {
  Data: { color: '#06B6D4', label: 'Data' },
  Dev: { color: '#8B5CF6', label: 'Dev' },
  Design: { color: '#EC4899', label: 'Design' },
  Video: { color: '#F59E0B', label: 'Video' },
};

export default ALL_TOOLS;
