import { CATEGORIES } from './categories';

/**
 * Single source of truth for all tech stack data.
 * slug → SimpleIcons CDN identifier (cdn.simpleicons.org/{slug}/{hex})
 * model → path to .glb file or '' for procedural shape
 * relations → ids of connected technologies (shown as lines on click)
 */
export const LOGOS_DATA = {

  // ─────────────────────────────────────────────
  // WEB / FULL STACK
  // ─────────────────────────────────────────────
  [CATEGORIES.FULLSTACK]: [
    {
      id: 'html',
      name: 'HTML5',
      slug: 'html5',
      model: '',
      color: '#E34F26',
      level: 'Expert',
      years: 4,
      lastUsed: '2025',
      desc: 'Semantic markup language that structures every web experience. Foundation of the entire web stack.',
      projects: ['Portfolio', 'Cinevix Works', 'Company Dashboard'],
      related: ['css', 'javascript', 'react'],
      tools: ['Semantic HTML', 'Accessibility', 'SEO'],
    },
    {
      id: 'css',
      name: 'CSS3',
      slug: 'css3',
      model: '',
      color: '#1572B6',
      level: 'Expert',
      years: 4,
      lastUsed: '2025',
      desc: 'Cascading Style Sheets for responsive, animated, and pixel-perfect visual design.',
      projects: ['Portfolio', 'Landing Pages', 'UI Components'],
      related: ['html', 'tailwindcss', 'react'],
      tools: ['Flexbox', 'Grid', 'Animations', 'Variables'],
    },
    {
      id: 'javascript',
      name: 'JavaScript',
      slug: 'javascript',
      model: '',
      color: '#F7DF1E',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Dynamic scripting language powering interactivity on the web. Core of every frontend and Node.js backend.',
      projects: ['Portfolio', 'E-Commerce Engine', 'Dashboard Analytics'],
      related: ['typescript', 'react', 'nodejs'],
      tools: ['ES2024', 'DOM API', 'Async/Await', 'Modules'],
    },
    {
      id: 'typescript',
      name: 'TypeScript',
      slug: 'typescript',
      model: '',
      color: '#3178C6',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Strongly typed superset of JavaScript. Catches bugs at compile time, improves DX at scale.',
      projects: ['Portfolio', 'E-Commerce Engine', 'API Service'],
      related: ['javascript', 'react', 'nextjs'],
      tools: ['Generics', 'Type Guards', 'Interfaces', 'Strict Mode'],
    },
    {
      id: 'react',
      name: 'React',
      slug: 'react',
      model: '',
      color: '#61DAFB',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Declarative, component-driven UI library by Meta. Powers modern SPAs and complex interactions.',
      projects: ['Portfolio', 'Dashboard Analytics', 'Movie Ticket App', 'E-Commerce'],
      related: ['nextjs', 'typescript', 'tailwindcss'],
      tools: ['Hooks', 'Context', 'Suspense', 'React Query'],
    },
    {
      id: 'nextjs',
      name: 'Next.js',
      slug: 'nextdotjs',
      model: '',
      color: '#FFFFFF',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Full-stack React framework with SSR, SSG, App Router, and edge-native APIs. Powers this portfolio.',
      projects: ['Portfolio', 'E-Commerce Engine', 'Agency Platform'],
      related: ['react', 'typescript', 'prisma'],
      tools: ['App Router', 'Server Actions', 'Image Optimization', 'Middleware'],
    },
    {
      id: 'tailwindcss',
      name: 'Tailwind CSS',
      slug: 'tailwindcss',
      model: '',
      color: '#06B6D4',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Utility-first CSS framework for rapid, consistent UI development without leaving HTML.',
      projects: ['Portfolio', 'Dashboard Analytics', 'Agency Platform'],
      related: ['css', 'react', 'nextjs'],
      tools: ['JIT', 'Custom Tokens', 'Responsive', 'Dark Mode'],
    },
    {
      id: 'laravel',
      name: 'Laravel',
      slug: 'laravel',
      model: '',
      color: '#FF2D20',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Elegant PHP web framework with expressive syntax, Eloquent ORM, and Blade templating.',
      projects: ['Company App', 'API Service', 'CMS Dashboard'],
      related: ['php', 'mysql'],
      tools: ['Eloquent', 'Blade', 'Artisan', 'Sanctum'],
    },
    {
      id: 'php',
      name: 'PHP',
      slug: 'php',
      model: '',
      color: '#777BB4',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Server-side scripting language still powering over 75% of the web. Foundation for Laravel.',
      projects: ['Company App', 'Legacy API'],
      related: ['laravel', 'mysql'],
      tools: ['OOP', 'Composer', 'PDO', 'REST APIs'],
    },
    {
      id: 'nodejs',
      name: 'Node.js',
      slug: 'nodedotjs',
      model: '',
      color: '#339933',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'JavaScript runtime built on Chrome V8 for building fast, scalable server-side applications.',
      projects: ['E-Commerce Backend', 'API Service', 'Dashboard Analytics'],
      related: ['javascript', 'prisma', 'postgres'],
      tools: ['Express', 'npm', 'Streams', 'Cluster'],
    },
    {
      id: 'mysql',
      name: 'MySQL',
      slug: 'mysql',
      model: '',
      color: '#4479A1',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Most widely used open-source relational database. Optimized queries, indexing, and transactions.',
      projects: ['Company App', 'Dashboard Analytics', 'E-Commerce Backend'],
      related: ['laravel', 'php', 'sql'],
      tools: ['Indexing', 'Transactions', 'Joins', 'Stored Procedures'],
    },
    {
      id: 'postgres',
      name: 'PostgreSQL',
      slug: 'postgresql',
      model: '',
      color: '#4169E1',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'Advanced open-source RDBMS with JSON support, full-text search, and ACID compliance.',
      projects: ['Portfolio', 'Agency Platform', 'E-Commerce Engine'],
      related: ['prisma', 'nodejs', 'sql'],
      tools: ['JSONB', 'Full-text Search', 'Extensions', 'Row-level Security'],
    },
    {
      id: 'prisma',
      name: 'Prisma',
      slug: 'prisma',
      model: '',
      color: '#5A67D8',
      level: 'Intermediate',
      years: 1,
      lastUsed: '2025',
      desc: 'Next-generation ORM for Node.js and TypeScript with type-safe database queries.',
      projects: ['Portfolio', 'Agency Platform'],
      related: ['postgres', 'nodejs', 'typescript'],
      tools: ['Schema', 'Migrations', 'Studio', 'Type Safety'],
    },
    {
      id: 'docker',
      name: 'Docker',
      slug: 'docker',
      model: '',
      color: '#2496ED',
      level: 'Intermediate',
      years: 1,
      lastUsed: '2025',
      desc: 'Container platform for building, shipping, and running isolated, reproducible environments.',
      projects: ['E-Commerce Engine', 'API Service'],
      related: ['nodejs', 'postgres'],
      tools: ['Docker Compose', 'Volumes', 'Networks', 'Multi-stage Builds'],
    },
    {
      id: 'git',
      name: 'Git',
      slug: 'git',
      model: '',
      color: '#F05032',
      level: 'Advanced',
      years: 4,
      lastUsed: '2025',
      desc: 'Distributed version control system. Foundation of every collaborative software project.',
      projects: ['All Projects'],
      related: ['github'],
      tools: ['Branching', 'Rebase', 'Cherry-pick', 'Hooks'],
    },
    {
      id: 'github',
      name: 'GitHub',
      slug: 'github',
      model: '',
      color: '#FFFFFF',
      level: 'Advanced',
      years: 4,
      lastUsed: '2025',
      desc: 'Code hosting, collaboration, and CI/CD platform. Where all projects live and are deployed from.',
      projects: ['All Projects'],
      related: ['git'],
      tools: ['Actions', 'Pages', 'Pull Requests', 'Code Review'],
    },
  ],

  // ─────────────────────────────────────────────
  // DATA ANALYST
  // ─────────────────────────────────────────────
  [CATEGORIES.DATA]: [
    {
      id: 'python',
      name: 'Python',
      slug: 'python',
      model: '',
      color: '#3776AB',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Primary language for data science, machine learning, and automation pipelines.',
      projects: ['E-Commerce Engine', 'Turnover Prediction', 'EDA Projects'],
      related: ['pandas', 'sklearn', 'fastapi'],
      tools: ['Data Science', 'ML', 'Automation', 'Scripting'],
    },
    {
      id: 'pandas',
      name: 'Pandas',
      slug: 'pandas',
      model: '',
      color: '#150458',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Fast, powerful, flexible data manipulation and analysis library. DataFrame-based workflows.',
      projects: ['EDA Projects', 'Turnover Prediction', 'Dashboard'],
      related: ['python', 'numpy', 'matplotlib'],
      tools: ['DataFrames', 'GroupBy', 'Merging', 'Reshaping'],
    },
    {
      id: 'numpy',
      name: 'NumPy',
      slug: 'numpy',
      model: '',
      color: '#013243',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'Fundamental numerical computing library for Python. N-dimensional arrays and linear algebra.',
      projects: ['ML Pipeline', 'EDA Projects'],
      related: ['python', 'pandas', 'sklearn'],
      tools: ['Arrays', 'Linear Algebra', 'Broadcasting', 'Vectorization'],
    },
    {
      id: 'matplotlib',
      name: 'Matplotlib',
      slug: 'matplotlib',
      model: '',
      color: '#11557C',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'Comprehensive library for creating static, animated, and interactive visualizations in Python.',
      projects: ['EDA Projects', 'Reporting'],
      related: ['python', 'pandas', 'numpy'],
      tools: ['Charts', 'Subplots', 'Custom Styles', 'Animations'],
    },
    {
      id: 'sql',
      name: 'SQL',
      slug: 'sqlite',
      model: '',
      color: '#003B57',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Structured Query Language for extracting, transforming, and analyzing relational data.',
      projects: ['Analytics DB', 'Reporting', 'Dashboard Analytics'],
      related: ['mysql', 'postgres', 'bigquery'],
      tools: ['Window Functions', 'CTEs', 'Subqueries', 'Aggregations'],
    },
    {
      id: 'powerbi',
      name: 'Power BI',
      slug: 'powerbi',
      model: '',
      color: '#F2C811',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Microsoft business intelligence suite for interactive dashboards and enterprise reporting.',
      projects: ['Sales Dashboard', 'KPI Report', 'E-Commerce Analytics'],
      related: ['excel', 'sql', 'looker'],
      tools: ['DAX', 'Power Query', 'Data Modeling', 'Publish to Web'],
    },
    {
      id: 'looker',
      name: 'Looker Studio',
      slug: 'looker',
      model: '',
      color: '#4285F4',
      level: 'Advanced',
      years: 2,
      lastUsed: '2025',
      desc: 'Google analytics and visualization tool connected to BigQuery, Sheets, and GA4.',
      projects: ['Marketing Report', 'E-Commerce Dashboard'],
      related: ['bigquery', 'sql', 'powerbi'],
      tools: ['Calculated Fields', 'Blended Data', 'GA4', 'Scheduled Reports'],
    },
    {
      id: 'excel',
      name: 'Excel',
      slug: 'microsoftexcel',
      model: '',
      color: '#217346',
      level: 'Expert',
      years: 4,
      lastUsed: '2025',
      desc: 'Industry-standard spreadsheet: pivot tables, Power Query, Power Pivot, and advanced functions.',
      projects: ['Financial Report', 'EDA Projects', 'Sales Analysis'],
      related: ['powerbi', 'sql'],
      tools: ['Pivot Tables', 'Power Query', 'XLOOKUP', 'Data Validation'],
    },
    {
      id: 'sklearn',
      name: 'Scikit-learn',
      slug: 'scikitlearn',
      model: '',
      color: '#F7931E',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'Machine learning library for classification, regression, clustering, and model evaluation.',
      projects: ['Turnover Prediction', 'E-Commerce Engine'],
      related: ['python', 'pandas', 'numpy'],
      tools: ['Random Forest', 'SVM', 'Cross-validation', 'Pipeline'],
    },
    {
      id: 'bigquery',
      name: 'BigQuery',
      slug: 'googlebigquery',
      model: '',
      color: '#4285F4',
      level: 'Intermediate',
      years: 1,
      lastUsed: '2025',
      desc: 'Google Cloud serverless data warehouse for large-scale analytics with SQL.',
      projects: ['Marketing Analytics', 'GA4 Pipeline'],
      related: ['sql', 'looker'],
      tools: ['Partitioning', 'Clustering', 'ML in SQL', 'Scheduled Queries'],
    },
    {
      id: 'fastapi',
      name: 'FastAPI',
      slug: 'fastapi',
      model: '',
      color: '#009688',
      level: 'Intermediate',
      years: 1,
      lastUsed: '2025',
      desc: 'Modern, async Python API framework. Powers the recommendation engine backend.',
      projects: ['E-Commerce Engine', 'ML API'],
      related: ['python', 'postgres'],
      tools: ['Pydantic', 'Async', 'Auto Docs', 'OAuth2'],
    },
  ],

  // ─────────────────────────────────────────────
  // GRAPHIC DESIGN
  // ─────────────────────────────────────────────
  [CATEGORIES.DESIGN]: [
    {
      id: 'figma',
      name: 'Figma',
      slug: 'figma',
      model: '',
      color: '#F24E1E',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Collaborative UI/UX design and prototyping tool. Used for every digital product in this portfolio.',
      projects: ['Portfolio UI', 'App Mockups', 'Design Systems'],
      related: ['illustrator', 'photoshop', 'canva'],
      tools: ['Components', 'Auto Layout', 'Prototyping', 'Dev Mode'],
    },
    {
      id: 'photoshop',
      name: 'Photoshop',
      slug: 'adobephotoshop',
      model: '',
      color: '#31A8FF',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Industry-standard raster editing for photo retouching, compositing, and digital art.',
      projects: ['Brand Design', 'Photo Editing', 'Social Media Content'],
      related: ['lightroom', 'illustrator'],
      tools: ['Masking', 'Smart Objects', 'Retouching', 'Compositing'],
    },
    {
      id: 'illustrator',
      name: 'Illustrator',
      slug: 'adobeillustrator',
      model: '',
      color: '#FF9A00',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Vector graphics editor for logos, illustrations, and print-ready artwork.',
      projects: ['Logo Design', 'Brand Identity', 'Print Materials'],
      related: ['figma', 'photoshop', 'coreldraw'],
      tools: ['Pen Tool', 'Pathfinder', 'Typography', 'Artboards'],
    },
    {
      id: 'lightroom',
      name: 'Lightroom',
      slug: 'adobelightroom',
      model: '',
      color: '#31A8FF',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Professional photo post-processing and color grading for photography portfolios and content.',
      projects: ['Photography Portfolio', 'Event Documentation'],
      related: ['photoshop'],
      tools: ['Color Grading', 'Presets', 'HSL', 'Batch Export'],
    },
    {
      id: 'coreldraw',
      name: 'CorelDRAW',
      slug: 'coreldraw',
      model: '',
      color: '#75B723',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Professional vector design suite for print, signage, and layout-heavy design work.',
      projects: ['Print Design', 'Brochure', 'Banner'],
      related: ['illustrator'],
      tools: ['Vector Tools', 'Page Layout', 'Print-ready', 'Color Management'],
    },
    {
      id: 'canva',
      name: 'Canva',
      slug: 'canva',
      model: '',
      color: '#00C4CC',
      level: 'Expert',
      years: 4,
      lastUsed: '2025',
      desc: 'Rapid graphic design for social media, presentations, and marketing materials.',
      projects: ['Social Media Kit', 'Poster', 'Pitch Deck'],
      related: ['figma', 'photoshop'],
      tools: ['Templates', 'Brand Kit', 'Animations', 'Batch Resize'],
    },
  ],

  // ─────────────────────────────────────────────
  // VIDEOGRAPHER
  // ─────────────────────────────────────────────
  [CATEGORIES.VIDEO]: [
    {
      id: 'premiere',
      name: 'Premiere Pro',
      slug: 'adobepremierepro',
      model: '',
      color: '#9999FF',
      level: 'Advanced',
      years: 3,
      lastUsed: '2025',
      desc: 'Industry-standard non-linear video editor for professional film and content production.',
      projects: ['SINEDEK Short Film', 'Brand Video', 'Event Documentation'],
      related: ['aftereffects', 'audition', 'mediaencoder'],
      tools: ['Multi-cam', 'Color Correction', 'Effects', 'Export Presets'],
    },
    {
      id: 'aftereffects',
      name: 'After Effects',
      slug: 'adobeaftereffects',
      model: '',
      color: '#9999FF',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Motion graphics and visual effects compositing. Used for title sequences and animations.',
      projects: ['Motion Intro', 'Title Cards', 'SINEDEK Film'],
      related: ['premiere', 'mediaencoder'],
      tools: ['Keyframing', 'Expressions', 'Shape Layers', 'Compositions'],
    },
    {
      id: 'davinci',
      name: 'DaVinci Resolve',
      slug: 'davinciresolve',
      model: '',
      color: '#CE2029',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2025',
      desc: 'Professional color science and video editing suite used by Hollywood productions.',
      projects: ['SINEDEK Short Film', 'Color Grading Projects'],
      related: ['premiere'],
      tools: ['Color Wheels', 'Nodes', 'Fusion', 'Fairlight'],
    },
    {
      id: 'capcut',
      name: 'CapCut',
      slug: 'tiktok',
      model: '',
      color: '#69C9D0',
      level: 'Expert',
      years: 3,
      lastUsed: '2025',
      desc: 'Fast, intuitive video creation for social media content — Reels, TikTok, YouTube Shorts.',
      projects: ['Social Content', 'Reels', 'YouTube Shorts'],
      related: ['premiere'],
      tools: ['Auto Captions', 'Speed Ramp', 'Transitions', 'AI Tools'],
    },
    {
      id: 'audition',
      name: 'Adobe Audition',
      slug: 'adobeaudition',
      model: '',
      color: '#9999FF',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Professional digital audio workstation for mixing, mastering, and noise reduction.',
      projects: ['SINEDEK Film', 'Podcast Edit'],
      related: ['premiere', 'mediaencoder'],
      tools: ['Noise Reduction', 'Multitrack', 'Spectral View', 'Mastering'],
    },
    {
      id: 'mediaencoder',
      name: 'Media Encoder',
      slug: 'adobemediaencoder',
      model: '',
      color: '#9999FF',
      level: 'Intermediate',
      years: 2,
      lastUsed: '2024',
      desc: 'Background encoding and batch export for Premiere Pro and After Effects projects.',
      projects: ['All Video Projects'],
      related: ['premiere', 'aftereffects'],
      tools: ['Presets', 'Queue', 'H.264', 'ProRes'],
    },
  ],
};
